# Generated by Django 3.2.7 on 2021-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcountry',
            name='continent',
            field=models.CharField(default=1, max_length=50, verbose_name='Continent'),
            preserve_default=False,
        ),
    ]
